rules = [
    (r'from', 'FROM'),
    (r'import', 'IMPORT'),
    (r'as', 'AS'),
    (r'class', 'CLASS'),
    (r'def', 'DEF'),
    (r'return', 'RETURN'),
    (r'pass', 'PASS'),
    (r'raise', 'RAISE'),
    (r'continue', 'CONTINUE'),
    (r'break', 'BREAK'),
    (r'if', 'IF'),
    (r'elif', 'ELIF'),
    (r'else', 'ELSE'),
    (r'for', 'FOR'),
    (r'in', 'IN'),
    (r'range', 'RANGE'),
    (r'while', 'WHILE'),
    (r'None', 'NONE'),
    (r'True', 'TRUE'),
    (r'False', 'FALSE'),
    (r'not', 'NOT'),
    (r'and', 'AND'),
    (r'or', 'OR'),
    (r'is', 'IS'),
    (r'with', 'WITH'),
    (r'(print|len|str|int|float)', 'FUNC'),
    ('\".+\"', 'STRING'),
    ('\'.+\'', 'STRING'),
    (r'\.', 'WITH_METHOD'),
    (r':', 'COLON'),
    (r'""".*"""', 'COMMENT'),
    (r'\#.*', 'COMMENT'),
    (r'\n', 'NEWLINE'),
    (r' ', 'WHITESPACE'),
    (r'\d+',             'NUMBER'),
    (r'[a-zA-Z_]+',    'IDENTIFIER'),
    # (r'[a-zA-Z_]\w+',    'IDENTIFIER'),
    (r'\+',              'PLUS'),
    (r'\-',              'MINUS'),
    (r'\*\*',              'POWER'),
    (r'\*',              'MULTIPLY'),
    (r'\/',              'DIVIDE'),
    (r'\(',              'LP'),
    (r'\)',              'RP'),
    (r'=',               'EQUALS'),
    (r',', 'COMA'),
    (r'>=', 'GREATER OR EQUAL THAN'),
    (r'>', 'GREATER THAN'),
    (r'<=', 'LESS OR EQUAL THAN'),
    (r'<', 'LESS THAN'),
]